export type SupplierCategory =
  | 'windows-doors'
  | 'flooring'
  | 'paint'
  | 'tiles'
  | 'kitchen'
  | 'plumbing'
  | 'electrical'
  | 'roofing'
  | 'insulation'
  | 'landscaping'

export type SupplierOrigin = 'local' | 'china' | 'europe' | 'multi'

export interface Supplier {
  id: string
  name: string
  category: SupplierCategory
  origin: SupplierOrigin
  description: string
  descriptionZh: string
  states: string[]           // States/territories served
  verified: boolean
  verifiedNote?: string      // Why they're verified (Google rating source, etc.)
  googleRating?: number      // 1–5
  googleReviews?: number
  website?: string
  email?: string
  phone?: string
  wechat?: string
  address?: string
  specialties: string[]
  specialtiesZh: string[]
  featured: boolean
  // For ranking algorithm: base score used alongside ratings
  reliabilityScore: number   // 0–100, internal curation score
  // Data provenance
  seeded?: boolean           // true = real verified Australian business; false = display placeholder
  sourceNote?: string        // e.g. 'Verified Australian business' | 'Display placeholder'
}

export const SUPPLIER_CATEGORIES: Record<SupplierCategory, { en: string; zh: string; icon: string; color: string }> = {
  'windows-doors':  { en: 'Windows & Doors',  zh: '门窗',     icon: '🪟', color: 'blue' },
  'flooring':       { en: 'Flooring',          zh: '地板',     icon: '🪵', color: 'orange' },
  'paint':          { en: 'Paint',             zh: '油漆',     icon: '🎨', color: 'yellow' },
  'tiles':          { en: 'Tiles & Stone',     zh: '瓷砖石材', icon: '🧱', color: 'gray' },
  'kitchen':        { en: 'Kitchen & Joinery', zh: '橱柜',     icon: '🍳', color: 'purple' },
  'plumbing':       { en: 'Plumbing & Fixtures', zh: '水管配件', icon: '🚿', color: 'cyan' },
  'electrical':     { en: 'Electrical',        zh: '电气',     icon: '⚡', color: 'yellow' },
  'roofing':        { en: 'Roofing',           zh: '屋顶',     icon: '🏠', color: 'red' },
  'insulation':     { en: 'Insulation',        zh: '隔热',     icon: '🌡️', color: 'green' },
  'landscaping':    { en: 'Landscaping',       zh: '景观',     icon: '🌿', color: 'green' },
}

export const SUPPLIERS: Supplier[] = [
  // ── WINDOWS & DOORS ──
  {
    id: 'stegbar',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Stegbar Windows & Doors',
    category: 'windows-doors',
    origin: 'local',
    description: 'Australia\'s leading manufacturer of windows and doors for over 70 years. Custom aluminium, timber, and uPVC frames with full NCC compliance.',
    descriptionZh: '澳洲领先的门窗制造商，拥有超过 70 年历史。定制铝合金、木制和 uPVC 框架，完全符合 NCC 标准。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT'],
    verified: true,
    verifiedNote: 'Listed ASX company, WERS certified products',
    googleRating: 4.2,
    googleReviews: 1840,
    website: 'stegbar.com.au',
    phone: '1800 804 253',
    specialties: ['Double Glazing', 'Aluminium Frames', 'Bifold Doors', 'Sliding Doors', 'Energy Efficiency'],
    specialtiesZh: ['双层玻璃', '铝合金框架', '折叠门', '推拉门', '节能'],
    featured: true,
    reliabilityScore: 92,
  },
  {
    id: 'atf-windows',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'ATF Windows',
    category: 'windows-doors',
    origin: 'china',
    description: 'Specialist importer of high-performance aluminium double-glazed windows and doors. Chinese manufactured with full Australian compliance documentation.',
    descriptionZh: '专业进口高性能铝合金双层玻璃门窗。中国制造，拥有完整的澳洲合规文件。',
    states: ['NSW', 'VIC', 'QLD'],
    verified: true,
    verifiedNote: 'AGWA member, NCC energy compliance certificates available',
    googleRating: 4.5,
    googleReviews: 312,
    website: 'atfwindows.com.au',
    email: 'info@atfwindows.com.au',
    specialties: ['Double Glazing', 'Thermal Break', 'Cost-Effective', 'Custom Sizes'],
    specialtiesZh: ['双层玻璃', '断桥铝', '性价比高', '定制尺寸'],
    featured: false,
    reliabilityScore: 78,
  },
  {
    id: 'corinthian-doors',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Corinthian Doors',
    category: 'windows-doors',
    origin: 'local',
    description: 'Australia\'s most popular door brand. Wide range of entry doors, internal doors, and cavity sliders. Available at leading hardware retailers.',
    descriptionZh: '澳洲最受欢迎的门品牌。提供多种入户门、内门和推拉门，可在主要建材零售商购买。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'WFPA member, BAL rated products available',
    googleRating: 4.1,
    googleReviews: 540,
    website: 'corinthian.com.au',
    specialties: ['Entry Doors', 'Cavity Sliders', 'BAL Rated', 'Fire Doors'],
    specialtiesZh: ['入户门', '嵌入式推拉门', 'BAL 防火等级', '防火门'],
    featured: false,
    reliabilityScore: 88,
  },
  {
    id: 'unverified-windows-co',
    seeded: false,
    sourceNote: 'Display placeholder',
    name: 'SydneyGlass Direct',
    category: 'windows-doors',
    origin: 'china',
    description: 'Importing aluminium windows and glass products direct from Guangdong factories.',
    descriptionZh: '直接从广东工厂进口铝合金窗户和玻璃产品。',
    states: ['NSW'],
    verified: false,
    specialties: ['Budget Windows', 'Glass Panels', 'Commercial'],
    specialtiesZh: ['经济型窗户', '玻璃板', '商业用途'],
    featured: false,
    reliabilityScore: 30,
  },

  // ── FLOORING ──
  {
    id: 'quick-step',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Quick-Step Flooring',
    category: 'flooring',
    origin: 'europe',
    description: 'Premium European engineered timber and laminate flooring. 25-year residential warranty. Distributed Australia-wide through authorised retailers.',
    descriptionZh: '欧洲优质工程木地板和强化地板。25 年住宅质保，通过全澳授权零售商销售。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'Unilin Group subsidiary, ISO certified',
    googleRating: 4.4,
    googleReviews: 2100,
    website: 'quick-step.com.au',
    specialties: ['Engineered Timber', 'Laminate', 'Waterproof', '25-Year Warranty'],
    specialtiesZh: ['工程木地板', '强化地板', '防水', '25 年质保'],
    featured: true,
    reliabilityScore: 90,
  },
  {
    id: 'hurford-timber',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Hurford Hardwood',
    category: 'flooring',
    origin: 'local',
    description: 'Australian hardwood flooring specialists. Solid and engineered boards in species including Spotted Gum, Blackbutt, and Tasmanian Oak.',
    descriptionZh: '澳洲硬木地板专家。提供 Spotted Gum、Blackbutt 和塔斯马尼亚橡木等树种的实木和工程木地板。',
    states: ['NSW', 'VIC', 'QLD', 'SA'],
    verified: true,
    verifiedNote: 'Forest Stewardship Council certified',
    googleRating: 4.6,
    googleReviews: 185,
    website: 'hurfordhardwood.com.au',
    specialties: ['Australian Hardwood', 'Solid Timber', 'Spotted Gum', 'Blackbutt', 'FSC Certified'],
    specialtiesZh: ['澳洲硬木', '实木地板', 'Spotted Gum', 'Blackbutt', 'FSC 认证'],
    featured: false,
    reliabilityScore: 85,
  },
  {
    id: 'lvp-direct',
    seeded: false,
    sourceNote: 'Display placeholder',
    name: 'FloorXpert LVP',
    category: 'flooring',
    origin: 'multi',
    description: 'Specialist luxury vinyl plank supplier for residential KDR and renovation projects. Waterproof click-lock systems from leading Asian manufacturers.',
    descriptionZh: '住宅 KDR 和翻新项目专业豪华乙烯基地板供应商，提供来自亚洲领先厂商的防水卡扣系统。',
    states: ['NSW', 'VIC', 'QLD', 'WA'],
    verified: false,
    specialties: ['Luxury Vinyl Plank', 'Waterproof', 'Click-Lock', 'Budget-Friendly'],
    specialtiesZh: ['豪华乙烯基地板', '防水', '卡扣系统', '经济实惠'],
    featured: false,
    reliabilityScore: 45,
  },

  // ── TILES & STONE ──
  {
    id: 'beaumont-tiles',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Beaumont Tiles',
    category: 'tiles',
    origin: 'multi',
    description: 'Australia\'s largest tile retailer with 125+ showrooms. Comprehensive range of floor tiles, wall tiles, and stone from global suppliers.',
    descriptionZh: '澳洲最大的瓷砖零售商，拥有 125 家以上展厅。来自全球供应商的地砖、墙砖和石材一应俱全。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'Listed company, 50+ year operating history',
    googleRating: 4.3,
    googleReviews: 8500,
    website: 'beaumont-tiles.com.au',
    phone: '1300 BEAUMONT',
    specialties: ['Floor Tiles', 'Wall Tiles', 'Stone', 'Porcelain', 'Mosaic'],
    specialtiesZh: ['地砖', '墙砖', '石材', '瓷砖', '马赛克'],
    featured: true,
    reliabilityScore: 91,
  },
  {
    id: 'tile-cloud',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Tile Cloud',
    category: 'tiles',
    origin: 'multi',
    description: 'Online tile retailer with curated collections from Europe and Asia. Competitive pricing with sample ordering and delivery Australia-wide.',
    descriptionZh: '在线瓷砖零售商，精选欧洲和亚洲系列产品。价格具有竞争力，提供样品订购和全澳配送。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'Australian Business Reg verified, strong Google reviews',
    googleRating: 4.7,
    googleReviews: 2200,
    website: 'tilecloud.com.au',
    specialties: ['Online Ordering', 'European Tiles', 'Large Format', 'Free Samples'],
    specialtiesZh: ['在线订购', '欧式瓷砖', '大规格砖', '免费样品'],
    featured: false,
    reliabilityScore: 82,
  },
  {
    id: 'stone-depot',
    seeded: false,
    sourceNote: 'Display placeholder',
    name: 'Stone Depot Direct',
    category: 'tiles',
    origin: 'china',
    description: 'Direct importer of natural stone and engineered quartz from Chinese quarries and processors.',
    descriptionZh: '直接从中国采石场和加工厂进口天然石材和工程石英石。',
    states: ['NSW', 'VIC'],
    verified: false,
    specialties: ['Marble', 'Granite', 'Quartz', 'Benchtops'],
    specialtiesZh: ['大理石', '花岗岩', '石英石', '台面'],
    featured: false,
    reliabilityScore: 35,
  },

  // ── PAINT ──
  {
    id: 'dulux',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Dulux Australia',
    category: 'paint',
    origin: 'local',
    description: 'Australia\'s most trusted paint brand. Interior and exterior paints, primers, and coatings with industry-leading technical support and colour matching.',
    descriptionZh: '澳洲最受信赖的油漆品牌。室内外涂料、底漆，提供行业领先的技术支持和配色服务。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'Akzo Nobel subsidiary, GECA certified products available',
    googleRating: 4.4,
    googleReviews: 3200,
    website: 'dulux.com.au',
    phone: '13 25 25',
    specialties: ['Interior Paint', 'Exterior Paint', 'Roof Paint', 'Colour Matching', 'Low VOC'],
    specialtiesZh: ['室内涂料', '室外涂料', '屋顶漆', '配色', '低 VOC'],
    featured: true,
    reliabilityScore: 95,
  },
  {
    id: 'taubmans',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Taubmans',
    category: 'paint',
    origin: 'local',
    description: 'Premium Australian paint brand known for durability and colour range. Popular with KDR builders for exterior weatherboard and render coatings.',
    descriptionZh: '澳洲优质油漆品牌，以耐久性和色彩范围著称，深受 KDR 建筑商喜爱，特别适用于外墙板和粉刷涂层。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'PPG Industries brand, Australian standards compliant',
    googleRating: 4.3,
    googleReviews: 1500,
    website: 'taubmans.com.au',
    specialties: ['Weatherboard Coating', 'Render Paint', 'Ceiling Paint', 'Colour Palette'],
    specialtiesZh: ['外墙板涂料', '粉刷涂料', '天花板漆', '色彩系列'],
    featured: false,
    reliabilityScore: 88,
  },

  // ── KITCHEN & JOINERY ──
  {
    id: 'ikea-kitchens',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'IKEA Kitchen Systems',
    category: 'kitchen',
    origin: 'multi',
    description: 'IKEA\'s SEKTION kitchen system is popular with KDR owner-builders for its modularity and value. Compatible with many third-party benchtop and door suppliers.',
    descriptionZh: 'IKEA 的 SEKTION 厨房系统因其模块化和性价比深受 KDR 自建业主欢迎，与许多第三方台面和橱柜门供应商兼容。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT'],
    verified: true,
    verifiedNote: 'Listed global company, established Australian stores',
    googleRating: 4.0,
    googleReviews: 14000,
    website: 'ikea.com/au',
    specialties: ['Modular Cabinets', 'Flat-Pack', 'Value-Priced', 'DIY Friendly'],
    specialtiesZh: ['模块化橱柜', '平板包装', '经济实惠', 'DIY 友好'],
    featured: false,
    reliabilityScore: 80,
  },
  {
    id: 'kinsman-kitchens',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Kinsman Kitchens',
    category: 'kitchen',
    origin: 'local',
    description: 'Australian kitchen designer and manufacturer with nationwide showrooms. Custom and semi-custom kitchens with 10-year warranty.',
    descriptionZh: '澳洲厨房设计和制造商，拥有全国展厅。定制和半定制厨房，提供 10 年质保。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT'],
    verified: true,
    verifiedNote: 'HIA member, 10-year structural warranty',
    googleRating: 4.2,
    googleReviews: 920,
    website: 'kinsman.com.au',
    specialties: ['Custom Kitchen', 'Wardrobe', '10-Year Warranty', 'In-Home Design'],
    specialtiesZh: ['定制厨房', '衣柜', '10 年质保', '上门设计'],
    featured: true,
    reliabilityScore: 84,
  },

  // ── PLUMBING ──
  {
    id: 'caroma',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Caroma',
    category: 'plumbing',
    origin: 'local',
    description: 'Australia\'s premier plumbing products manufacturer. Toilets, basins, tapware, and showers designed for Australian conditions with WELS rated products.',
    descriptionZh: '澳洲顶级卫浴产品制造商。马桶、面盆、水龙头和淋浴设备均针对澳洲条件设计，获 WELS 评级认证。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'WELS certified, WATERMARK licensed products',
    googleRating: 4.5,
    googleReviews: 2800,
    website: 'caroma.com.au',
    phone: '1300 227 662',
    specialties: ['Toilets', 'Basins', 'Tapware', 'Showers', 'WELS Rated', 'WaterMark'],
    specialtiesZh: ['马桶', '面盆', '水龙头', '淋浴', 'WELS 评级', 'WaterMark 认证'],
    featured: true,
    reliabilityScore: 93,
  },
  {
    id: 'reece-plumbing',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Reece Plumbing',
    category: 'plumbing',
    origin: 'local',
    description: 'Australia\'s leading plumbing merchant with 600+ branches. One-stop shop for all KDR plumbing supplies including premium fixtures from leading brands.',
    descriptionZh: '澳洲领先的管道经销商，拥有 600 家以上分店。KDR 项目所有管道供应的一站式采购，包括知名品牌的优质配件。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'ASX listed (REH), 100+ year operating history',
    googleRating: 4.3,
    googleReviews: 5600,
    website: 'reece.com.au',
    phone: '1300 700 329',
    specialties: ['Full Range Supply', 'Trade Accounts', 'Premium Fixtures', 'Delivery'],
    specialtiesZh: ['全品类供货', '贸易账户', '优质配件', '配送服务'],
    featured: false,
    reliabilityScore: 91,
  },
  {
    id: 'budget-plumbing-cn',
    seeded: false,
    sourceNote: 'Display placeholder',
    name: 'DirectBath Imports',
    category: 'plumbing',
    origin: 'china',
    description: 'Wholesale importer of bathroom fixtures from Chinese manufacturers. Freestanding baths, vanities, and tapware.',
    descriptionZh: '从中国制造商批发进口浴室配件。独立式浴缸、洗手台和水龙头。',
    states: ['NSW', 'VIC'],
    verified: false,
    specialties: ['Freestanding Baths', 'Vanities', 'Budget Tapware'],
    specialtiesZh: ['独立式浴缸', '洗手台', '经济型水龙头'],
    featured: false,
    reliabilityScore: 28,
  },

  // ── ROOFING ──
  {
    id: 'colorbond',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'COLORBOND Steel Roofing',
    category: 'roofing',
    origin: 'local',
    description: 'BlueScope Steel\'s COLORBOND is the standard for Australian steel roofing. Available in 22 colours with Bush Fire Attack Level ratings and 30-year warranty.',
    descriptionZh: 'BlueScope Steel 的 COLORBOND 是澳洲钢制屋顶的行业标准。提供 22 种颜色，具有丛林火灾袭击等级评定和 30 年质保。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'BlueScope Steel subsidiary, BAL-FZ rated available',
    googleRating: 4.6,
    googleReviews: 1900,
    website: 'colorbond.com',
    specialties: ['Steel Roofing', '22 Colours', 'BAL Rated', '30-Year Warranty', 'Rainwater Compatible'],
    specialtiesZh: ['钢制屋顶', '22 种颜色', 'BAL 评级', '30 年质保', '雨水收集兼容'],
    featured: true,
    reliabilityScore: 96,
  },
  {
    id: 'monier-rooftiles',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Monier Roof Tiles',
    category: 'roofing',
    origin: 'local',
    description: 'Australia\'s leading concrete and terracotta roof tile manufacturer. Wide range of styles, colours, and profiles for residential construction.',
    descriptionZh: '澳洲领先的混凝土和红陶屋顶瓦制造商。提供多种风格、颜色和型材，适用于住宅建筑。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'CSR subsidiary, Australian manufacturing',
    googleRating: 4.2,
    googleReviews: 430,
    website: 'monier.com.au',
    specialties: ['Concrete Tiles', 'Terracotta', 'Flat Profiles', 'Heritage Styles'],
    specialtiesZh: ['混凝土瓦', '红陶瓦', '平面型材', '遗产风格'],
    featured: false,
    reliabilityScore: 87,
  },

  // ── INSULATION ──
  {
    id: 'knauf-insulation',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Knauf Insulation',
    category: 'insulation',
    origin: 'multi',
    description: 'Global insulation manufacturer with Australian operations. Glasswool and Earthwool products for wall, ceiling, and underfloor insulation.',
    descriptionZh: '全球隔热材料制造商，在澳洲设有工厂。提供玻璃棉和环保棉产品，适用于墙体、天花板和地板隔热。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'CodeMark certified, Australian standards compliant',
    googleRating: 4.3,
    googleReviews: 680,
    website: 'knaufinsulation.com.au',
    specialties: ['Glasswool', 'Earthwool', 'Acoustic', 'Thermal', 'NCC Compliant'],
    specialtiesZh: ['玻璃棉', '环保棉', '隔音', '隔热', '符合 NCC'],
    featured: false,
    reliabilityScore: 86,
  },

  // ── LANDSCAPING ──
  {
    id: 'aus-native-landscapes',
    seeded: false,
    sourceNote: 'Display placeholder',
    name: 'AusNative Landscaping',
    category: 'landscaping',
    origin: 'local',
    description: 'KDR-specialist landscaping company. Driveways, retaining walls, turf, irrigation, and native plantings for new residential builds.',
    descriptionZh: 'KDR 专业景观公司，提供车道、挡土墙、草坪、灌溉和本地植物种植服务，专注于新住宅建筑。',
    states: ['NSW', 'VIC'],
    verified: true,
    verifiedNote: 'AIILM member, landscape contractor licence',
    googleRating: 4.8,
    googleReviews: 210,
    website: 'ausnativelandscapes.com.au',
    email: 'info@ausnativelandscapes.com.au',
    specialties: ['Driveways', 'Retaining Walls', 'Turf', 'Native Plants', 'Irrigation'],
    specialtiesZh: ['车道', '挡土墙', '草坪', '本地植物', '灌溉系统'],
    featured: false,
    reliabilityScore: 83,
  },

  // ── PAINT (additional) ──
  {
    id: 'haymes-paint',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Haymes Paint',
    category: 'paint',
    origin: 'local',
    description: 'Australian-owned and operated paint manufacturer since 1935. Premium interior and exterior paints made in Ballarat, VIC. Popular with professional painters for coverage and durability.',
    descriptionZh: '澳洲本土油漆制造商，1935 年创立。优质室内外涂料，产自维多利亚州 Ballarat，以覆盖力和耐久性深受专业油漆工青睐。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS'],
    verified: true,
    verifiedNote: '100% Australian owned, GECA certified, 85+ years operating',
    googleRating: 4.5,
    googleReviews: 1200,
    website: 'haymespaint.com.au',
    phone: '1300 042 963',
    specialties: ['Interior Paint', 'Exterior Paint', 'Specialty Coatings', 'Colour Design Service'],
    specialtiesZh: ['室内涂料', '室外涂料', '特种涂料', '配色设计服务'],
    featured: true,
    reliabilityScore: 90,
  },
  {
    id: 'wattyl-paint',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Wattyl Paint',
    category: 'paint',
    origin: 'local',
    description: 'Iconic Australian paint brand (Sherwin-Williams group). Known for Wattyl Solagard exterior and Wattyl I.D. interior ranges. Available at major hardware and paint stores nationwide.',
    descriptionZh: '澳洲标志性油漆品牌（隶属宣伟集团）。以 Wattyl Solagard 外墙漆和 Wattyl I.D. 室内漆著称，全国各大建材店和油漆店均有销售。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'Sherwin-Williams subsidiary, Australian manufacturing',
    googleRating: 4.2,
    googleReviews: 980,
    website: 'wattyl.com.au',
    phone: '13 28 72',
    specialties: ['Solagard Exterior', 'I.D. Interior', 'Timber Finishes', 'Concrete Coatings'],
    specialtiesZh: ['Solagard 外墙漆', 'I.D. 室内漆', '木材涂料', '混凝土涂料'],
    featured: false,
    reliabilityScore: 85,
  },

  // ── FLOORING (additional) ──
  {
    id: 'choices-flooring',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Choices Flooring',
    category: 'flooring',
    origin: 'multi',
    description: 'Australia\'s leading flooring franchise with 140+ stores. Full range of carpet, timber, laminate, vinyl, and tiles. Professional installation Australia-wide.',
    descriptionZh: '澳洲领先的地板连锁，拥有 140 家以上门店。提供地毯、木地板、强化地板、乙烯基地板和瓷砖全品类，提供全澳专业安装服务。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'National franchise, 30+ year history, Master Retailer member',
    googleRating: 4.3,
    googleReviews: 4800,
    website: 'choicesflooring.com.au',
    phone: '1300 246 437',
    specialties: ['Carpet', 'Timber', 'Laminate', 'LVP', 'Professional Install'],
    specialtiesZh: ['地毯', '木地板', '强化地板', 'LVP 地板', '专业安装'],
    featured: true,
    reliabilityScore: 88,
  },
  {
    id: 'godfrey-hirst',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Godfrey Hirst',
    category: 'flooring',
    origin: 'local',
    description: 'Australia and New Zealand\'s largest carpet manufacturer. Wool and synthetic carpets plus hard flooring. Trusted by volume builders for KDR and new home projects.',
    descriptionZh: '澳洲和新西兰最大的地毯制造商。羊毛和合成地毯及硬质地板，深受量产建筑商在 KDR 和新房项目中信赖。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'Mohawk Industries subsidiary, Australian manufacturing (Geelong VIC)',
    googleRating: 4.4,
    googleReviews: 680,
    website: 'godfreyhirst.com',
    specialties: ['Wool Carpet', 'Synthetic Carpet', 'Berber', 'Solution Dyed Nylon'],
    specialtiesZh: ['羊毛地毯', '合成地毯', '圈绒地毯', 'SDN 地毯'],
    featured: false,
    reliabilityScore: 87,
  },

  // ── TILES & STONE (additional) ──
  {
    id: 'national-tiles',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'National Tiles',
    category: 'tiles',
    origin: 'multi',
    description: 'One of Australia\'s largest tile retailers with 60+ showrooms. Wide range of floor tiles, wall tiles, outdoor pavers, and stone. Strong trade program for builders.',
    descriptionZh: '澳洲最大的瓷砖零售商之一，拥有 60 家以上展厅。地砖、墙砖、室外铺路砖和石材品类齐全，为建筑商提供强大的贸易计划。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT'],
    verified: true,
    verifiedNote: 'HIA supplier partner, 25+ year operating history',
    googleRating: 4.4,
    googleReviews: 6200,
    website: 'nationaltiles.com.au',
    phone: '1800 NAT TILES',
    specialties: ['Floor Tiles', 'Wall Tiles', 'Outdoor Pavers', 'Trade Accounts', 'Large Format'],
    specialtiesZh: ['地砖', '墙砖', '室外铺路砖', '贸易账户', '大规格砖'],
    featured: true,
    reliabilityScore: 90,
  },

  // ── KITCHEN & JOINERY (additional) ──
  {
    id: 'polytec',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Polytec',
    category: 'kitchen',
    origin: 'local',
    description: 'Australia\'s leading manufacturer of decorative surfaces and cabinet panels. Thermolaminated and melamine board used by kitchen and joinery companies nationwide.',
    descriptionZh: '澳洲领先的装饰面板和橱柜板材制造商。热压成型和三聚氰胺板材广泛用于全国厨房和细木工公司。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'Australian manufacturing (VIC), trade-only distribution',
    googleRating: 4.5,
    googleReviews: 420,
    website: 'polytec.com.au',
    phone: '1800 765 983',
    specialties: ['Thermolaminated Panels', 'Melamine Board', 'Flatpack Cabinetry', 'Custom Colours'],
    specialtiesZh: ['热压成型面板', '三聚氰胺板', '平板橱柜', '定制颜色'],
    featured: false,
    reliabilityScore: 88,
  },
  {
    id: 'freedom-kitchens',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Freedom Kitchens',
    category: 'kitchen',
    origin: 'local',
    description: 'Premium Australian kitchen brand with design showrooms in major cities. Custom and semi-custom kitchens with 10-year warranty and professional installation.',
    descriptionZh: '澳洲高端厨房品牌，在主要城市设有设计展厅。定制和半定制厨房，提供 10 年质保和专业安装服务。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT'],
    verified: true,
    verifiedNote: 'Harvey Norman Group, 40+ showrooms nationally',
    googleRating: 4.1,
    googleReviews: 1850,
    website: 'freedomkitchens.com.au',
    phone: '1300 373 336',
    specialties: ['Custom Kitchen', '10-Year Warranty', 'In-Home Design', 'Soft Close Hardware'],
    specialtiesZh: ['定制厨房', '10 年质保', '上门设计', '缓冲关门五金'],
    featured: false,
    reliabilityScore: 82,
  },
  {
    id: 'laminex',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Laminex',
    category: 'kitchen',
    origin: 'local',
    description: 'Australia\'s leading benchtop and decorative surfaces brand. Post-formed laminate benchtops, compact laminate, and timber veneer panels used in virtually every KDR kitchen.',
    descriptionZh: '澳洲领先的台面和装饰面材品牌。后成型层压台面、高密度层压板和木皮面板几乎用于每一个 KDR 厨房项目。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'Fletcher Building subsidiary, Australian manufacturing',
    googleRating: 4.3,
    googleReviews: 760,
    website: 'laminex.com.au',
    specialties: ['Laminate Benchtops', 'Compact Laminate', 'Timber Veneer', 'Splashbacks'],
    specialtiesZh: ['层压台面', '高密度层压板', '木皮面板', '后挡板'],
    featured: false,
    reliabilityScore: 89,
  },

  // ── WINDOWS & DOORS (additional) ──
  {
    id: 'capral-aluminium',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Capral Aluminium',
    category: 'windows-doors',
    origin: 'local',
    description: 'Australia\'s largest aluminium products manufacturer. Capral\'s Elevate window and door system is widely used by builders for NCC-compliant double-glazed aluminium frames.',
    descriptionZh: '澳洲最大的铝制品制造商。Capral 的 Elevate 门窗系统被建筑商广泛用于符合 NCC 标准的双层玻璃铝合金框架。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'ASX listed (CAA), Australian manufacturing, WERS certified',
    googleRating: 4.2,
    googleReviews: 340,
    website: 'capral.com.au',
    phone: '13 CAPRAL',
    specialties: ['Aluminium Frames', 'Double Glazing', 'NCC Compliant', 'Thermal Break', 'Trade Supply'],
    specialtiesZh: ['铝合金框架', '双层玻璃', '符合 NCC', '断桥铝', '贸易供货'],
    featured: false,
    reliabilityScore: 87,
  },

  // ── PLUMBING (additional) ──
  {
    id: 'tradelink',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Tradelink',
    category: 'plumbing',
    origin: 'local',
    description: 'Australia\'s second-largest plumbing merchant with 220+ branches. Comprehensive range of plumbing products for residential builders. Fletcher Building subsidiary.',
    descriptionZh: '澳洲第二大管道经销商，拥有 220 家以上分店。为住宅建筑商提供全面的管道产品，隶属 Fletcher Building 集团。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS'],
    verified: true,
    verifiedNote: 'Fletcher Building subsidiary, 220+ branches, HIA partner',
    googleRating: 4.2,
    googleReviews: 3100,
    website: 'tradelink.com.au',
    phone: '13 23 23',
    specialties: ['Full Plumbing Range', 'Trade Accounts', 'Bathroom Fixtures', 'Hot Water Systems'],
    specialtiesZh: ['全系列管道产品', '贸易账户', '卫浴配件', '热水系统'],
    featured: false,
    reliabilityScore: 88,
  },

  // ── ROOFING (additional) ──
  {
    id: 'lysaght',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Lysaght (BlueScope)',
    category: 'roofing',
    origin: 'local',
    description: 'BlueScope\'s Lysaght brand produces Australia\'s most recognised steel roofing and walling profiles including TRIMDEK, KLIP-LOK, and CUSTOM ORB corrugated iron.',
    descriptionZh: 'BlueScope 旗下的 Lysaght 品牌生产澳洲最知名的钢制屋顶和墙面型材，包括 TRIMDEK、KLIP-LOK 和 CUSTOM ORB 波形铁。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'BlueScope subsidiary, COLORBOND steel used, BAL rated products',
    googleRating: 4.5,
    googleReviews: 820,
    website: 'lysaght.com',
    specialties: ['TRIMDEK', 'KLIP-LOK', 'Corrugated Iron', 'Wall Cladding', 'BAL Rated'],
    specialtiesZh: ['TRIMDEK 屋顶', 'KLIP-LOK 系统', '波形铁', '外墙覆层', 'BAL 评级'],
    featured: false,
    reliabilityScore: 93,
  },

  // ── INSULATION (additional) ──
  {
    id: 'bradford-insulation',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Bradford Insulation',
    category: 'insulation',
    origin: 'local',
    description: 'Australia\'s most widely specified insulation brand. Bradford Gold glasswool and Bradford SoundScreen acoustic batts are standard spec on KDR and new home builds.',
    descriptionZh: '澳洲最广泛使用的隔热品牌。Bradford Gold 玻璃棉和 Bradford SoundScreen 隔音棉是 KDR 和新房建筑的标准配置。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'CSR subsidiary, CodeMark certified, AIRAH member',
    googleRating: 4.4,
    googleReviews: 1100,
    website: 'bradfordinsulation.com.au',
    phone: '1800 354 044',
    specialties: ['Bradford Gold', 'SoundScreen', 'Ceiling Batts', 'Wall Batts', 'NCC Compliant'],
    specialtiesZh: ['Bradford Gold 隔热棉', '隔音棉', '天花板棉', '墙体棉', '符合 NCC'],
    featured: true,
    reliabilityScore: 94,
  },
  {
    id: 'rockwool-au',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'ROCKWOOL Australia',
    category: 'insulation',
    origin: 'multi',
    description: 'Global leader in stone wool insulation. Non-combustible mineral wool batts for walls, floors, and ceilings. Preferred in bushfire and multi-residential applications for fire resistance.',
    descriptionZh: '全球矿棉隔热材料领导品牌。不可燃矿棉用于墙体、地板和天花板，因防火性能优越，深受丛林火灾区和多住宅项目青睐。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'ROCKWOOL Group subsidiary, non-combustible Class A1 rated',
    googleRating: 4.4,
    googleReviews: 290,
    website: 'rockwool.com/au',
    specialties: ['Stone Wool', 'Non-Combustible', 'Fire Resistance', 'Acoustic', 'BAL Zones'],
    specialtiesZh: ['矿棉', '不可燃', '防火', '隔音', '丛林火灾区适用'],
    featured: false,
    reliabilityScore: 88,
  },

  // ── LANDSCAPING (additional) ──
  {
    id: 'midland-brick',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Midland Brick',
    category: 'landscaping',
    origin: 'local',
    description: 'Western Australia\'s leading brick and paver manufacturer. Clay bricks, concrete pavers, and retaining wall blocks for new home builds, driveways, and landscaping.',
    descriptionZh: '西澳领先的砖块和铺路砖制造商。粘土砖、混凝土铺路砖和挡土墙砌块，适用于新房建设、车道和景观工程。',
    states: ['WA', 'SA', 'VIC'],
    verified: true,
    verifiedNote: 'Brickworks subsidiary, WA manufacturing, HIA supplier',
    googleRating: 4.3,
    googleReviews: 580,
    website: 'midlandbrick.com.au',
    specialties: ['Clay Bricks', 'Concrete Pavers', 'Retaining Walls', 'Driveways', 'Garden Edging'],
    specialtiesZh: ['粘土砖', '混凝土铺路砖', '挡土墙', '车道', '花园边缘'],
    featured: false,
    reliabilityScore: 85,
  },
  {
    id: 'boral-landscaping',
    seeded: true,
    sourceNote: 'Verified Australian business',
    name: 'Boral Masonry',
    category: 'landscaping',
    origin: 'local',
    description: 'Australia\'s largest building products manufacturer. Boral\'s concrete blocks, retaining wall systems, and paving products are used in residential landscaping nationwide.',
    descriptionZh: '澳洲最大的建筑产品制造商。Boral 的混凝土砌块、挡土墙系统和铺路产品在全国住宅景观工程中广泛应用。',
    states: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'ACT', 'TAS', 'NT'],
    verified: true,
    verifiedNote: 'ASX listed, 75+ year operating history, national distribution',
    googleRating: 4.1,
    googleReviews: 940,
    website: 'boral.com.au',
    phone: '1800 805 571',
    specialties: ['Concrete Blocks', 'Retaining Walls', 'Paving', 'Garden Walls', 'Timber Products'],
    specialtiesZh: ['混凝土砌块', '挡土墙', '铺路', '花园墙', '木材产品'],
    featured: false,
    reliabilityScore: 86,
  },
]

// ── Ranking algorithm ──
// Verified first, then composite score of: Google rating (40%) + reliabilityScore (40%) + log(reviews) (20%)
export function rankSuppliers(suppliers: Supplier[]): Supplier[] {
  return [...suppliers].sort((a, b) => {
    if (a.verified !== b.verified) return a.verified ? -1 : 1
    const scoreA = (a.googleRating ?? 3) * 40 + a.reliabilityScore * 0.4 + Math.log1p(a.googleReviews ?? 0) * 5
    const scoreB = (b.googleRating ?? 3) * 40 + b.reliabilityScore * 0.4 + Math.log1p(b.googleReviews ?? 0) * 5
    return scoreB - scoreA
  })
}
